#!/bin/sh

set -e

FWUP_CONFIG=$PERIDIO_DEFCONFIG_DIR/fwup.conf
FWUP_REVERT_CONFIG=$PERIDIO_DEFCONFIG_DIR/fwup-revert.conf
$BR2_EXTERNAL_PERIDIO_AVOCADO_PATH/board/avocado-common/post-createfs.sh $TARGET_DIR $FWUP_CONFIG $FWUP_REVERT_CONFIG

